### ISSUE TITLE
too empty 

### ISSUE THREAD

**Issue by ender1324** [Minabsapi/AndROMega#2]
man wtf am I supposted to do here, I see only read me and thats it HELP HELP I NEED APAPAP IRIHEULJER

**Comment by Minabsapi** [comment]
i dont know, oh my god its the first time i do this pls help meeeeeeeeeee :'(

**Comment by ender1324** [comment]
AAAAAAAAAAAAAAAAAAAA I WANT LOS 18 ON MY PC RN BUIDL Q 2929 REEEEEEEEEEEEEEEEEEE

**Comment by Minabsapi** [comment]
ull have it just stop shouting at me please :'(

**Comment by ender1324** [comment]
oke have github cat
![GitHub-Mark-120px-plus](https://user-images.githubusercontent.com/46723422/60050372-27b8c180-96d9-11e9-8459-1675f853055e.png)

**Comment by Minabsapi** [comment]
that's not even a cat :(

**Comment by ender1324** [comment]
omg u not helping I will report to microsoft you will get beaned from the orld
